# User and group information
user = "holo"
group = "holo"

# Path to the non-volatile memory storage for configuration transactions,
# graceful-restart information, authentication sequence numbers, and more.
#
# Needs to be writable by @user or @group.
database_path = "/var/run/holo/holo.db"

# Logging configuration
[logging]
  # Logging to journald
  [logging.journald]
    # Enable or disable
    enabled = false

  # # Logging to a file
  [logging.file]
  # Enable or disable
    enabled = false
  #   # File path (needs to be writable by @user or @group)
    # dir = "/var/log/"
  #   # File name
  #   name = "holod.log"
  #   # Log rotation (options: "never", "daily", "hourly")
  #   rotation = "never"
  #   # Logging style (options: "full", "compact", "pretty", "json")
  #   style = "full"
  #   # Enable or disable ANSI terminal colors
  #   colors = false
  #   # Sets whether or not the thread ID of the current thread is displayed
  #   show_thread_id = false
  #   # Sets whether or not an event’s source code file path and line number are displayed
  #   show_source = false

  # Logging to the standard output
  [logging.stdout]
    # Enable or disable
    enabled = true
    # Logging style (options: "full", "compact", "pretty", "json")
    style = "full"
    # Enable or disable ANSI terminal colors
    colors = false
    # Sets whether or not the thread ID of the current thread is displayed
    show_thread_id = false
    # Sets whether or not an event’s source code file path and line number are displayed
    show_source = false

