system {
    login {
        user admin {
            uid 500;
            class superuser;
            authentication {
            encrypted-password "$6$9YSzwiCD$ZiMI1N.5fcWCe5fH8hZz/FtISY4K8QKjv9p0w6Hkyct71ke1bn3OQQk0oi7/l5Sn8yP1CClO9CeGSMpNQcFjT/"; ## SECRET-DATA
            }
        }
    }
    management-instance;
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
    services {
        netconf {
            ssh;
        }
        ssh {
            root-login allow;
        }
    }
}
interfaces {
    et-0/0/0 {
        unit 0 {
            family inet {
                address 10.0.4.5/24;
            }
        }
    }
    et-0/0/1 {
        unit 0 {
            family inet {
                address 10.0.5.5/24;
            }
        }
    }
    et-0/0/2 {
        unit 0 {
            family inet {
                address 10.0.6.5/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 5.5.5.5/32;
            }
        }
    }
    re0:mgmt-0 {
        unit 0 {
            family inet {
                address FXP0ADDR;
            }
        }
    }
}
routing-options {
    router-id 5.5.5.5;
}
protocols {
    ospf {
        area 0.0.0.0 {
            virtual-link neighbor-id 2.2.2.2 transit-area 0.0.0.1;
        }
        area 0.0.0.1 {
            interface et-0/0/0.0 {
                interface-type p2p;
                hello-interval 3;
                dead-interval 12;
            }
            interface et-0/0/1.0 {
                interface-type p2p;
                hello-interval 3;
                dead-interval 12;
            }
        }
        area 0.0.0.2 {
            interface et-0/0/2.0 {
                interface-type p2p;
                hello-interval 3;
                dead-interval 12;
            }
            interface lo0.0;
        }
    }
}
