set / interface ethernet-1/1
set / interface ethernet-1/1 subinterface 0
set / interface ethernet-1/1 subinterface 0 ipv4
set / interface ethernet-1/1 subinterface 0 ipv4 address 10.0.1.1/24
set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable

set / interface ethernet-1/2
set / interface ethernet-1/2 subinterface 0
set / interface ethernet-1/2 subinterface 0 ipv4
set / interface ethernet-1/2 subinterface 0 ipv4 address 10.0.2.1/24
set / interface ethernet-1/2 subinterface 0 ipv4 admin-state enable

set / interface ethernet-1/3
set / interface ethernet-1/3 subinterface 0
set / interface ethernet-1/3 subinterface 0 ipv4
set / interface ethernet-1/3 subinterface 0 ipv4 address 10.0.3.1/24
set / interface ethernet-1/3 subinterface 0 ipv4 admin-state enable

set / interface lo1
set / interface lo1 subinterface 0
set / interface lo1 subinterface 0 ipv4
set / interface lo1 subinterface 0 ipv4 address 1.1.1.1/32
set / interface lo1 subinterface 0 ipv4 admin-state enable

set / network-instance default
set / network-instance default interface ethernet-1/1.0
set / network-instance default interface ethernet-1/2.0
set / network-instance default interface ethernet-1/3.0
set / network-instance default interface lo1.0

set / network-instance default
set / network-instance default protocols
set / network-instance default protocols bgp
set / network-instance default protocols bgp router-id 1.1.1.1
set / network-instance default protocols bgp autonomous-system 65001
set / network-instance default protocols bgp afi-safi ipv4-unicast admin-state enable
set / network-instance default protocols bgp group GROUP
set / network-instance default protocols bgp group GROUP admin-state enable
set / network-instance default protocols bgp group GROUP export-policy ALL
set / network-instance default protocols bgp group GROUP import-policy ALL
set / network-instance default protocols bgp neighbor 10.0.1.2 peer-group GROUP
set / network-instance default protocols bgp neighbor 10.0.1.2 peer-as 65002
set / network-instance default protocols bgp neighbor 10.0.2.4 peer-group GROUP
set / network-instance default protocols bgp neighbor 10.0.2.4 peer-as 65004
set / network-instance default protocols bgp neighbor 10.0.3.5 peer-group GROUP
set / network-instance default protocols bgp neighbor 10.0.3.5 peer-as 65005

set / routing-policy
set / routing-policy policy ALL
set / routing-policy policy ALL default-action
set / routing-policy policy ALL default-action policy-result accept
