set / interface ethernet-1/1
set / interface ethernet-1/1 subinterface 0
set / interface ethernet-1/1 subinterface 0 ipv4
set / interface ethernet-1/1 subinterface 0 ipv4 address 10.0.7.6/24
set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable
set / interface ethernet-1/1 subinterface 0 ipv6
set / interface ethernet-1/1 subinterface 0 ipv6 admin-state enable

set / interface ethernet-1/2
set / interface ethernet-1/2 subinterface 0
set / interface ethernet-1/2 subinterface 0 ipv4
set / interface ethernet-1/2 subinterface 0 ipv4 address 10.0.8.6/24
set / interface ethernet-1/2 subinterface 0 ipv4 admin-state enable
set / interface ethernet-1/2 subinterface 0 ipv6
set / interface ethernet-1/2 subinterface 0 ipv6 admin-state enable

set / interface lo1
set / interface lo1 subinterface 0
set / interface lo1 subinterface 0 ipv4
set / interface lo1 subinterface 0 ipv4 address 6.6.6.6/32
set / interface lo1 subinterface 0 ipv4 admin-state enable
set / interface lo1 subinterface 0 ipv6
set / interface lo1 subinterface 0 ipv6 admin-state enable
set / interface lo1 subinterface 0 ipv6 address 2001:db8::6/128

set / network-instance default
set / network-instance default interface ethernet-1/1.0
set / network-instance default interface ethernet-1/2.0
set / network-instance default interface lo1.0

set / network-instance default
set / network-instance default protocols
set / network-instance default protocols isis
set / network-instance default protocols isis instance 1
set / network-instance default protocols isis instance 1 admin-state enable
set / network-instance default protocols isis instance 1 net [49.0000.0000.0000.0006.00]
set / network-instance default protocols isis instance 1 level-capability L1L2
set / network-instance default protocols isis instance 1 max-ecmp-paths 4
set / network-instance default protocols isis instance 1 interface ethernet-1/1.0
set / network-instance default protocols isis instance 1 interface ethernet-1/1.0 circuit-type point-to-point
set / network-instance default protocols isis instance 1 interface ethernet-1/2.0
set / network-instance default protocols isis instance 1 interface ethernet-1/2.0 circuit-type point-to-point
set / network-instance default protocols isis instance 1 interface lo1.0
